# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amictl < Formula
  desc "amictl"
  homepage "https://github.com/bwagner5/amictl"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.1/amictl_0.0.1_darwin_amd64.tar.gz"
      sha256 "e0cb061af0b6bb4b675e397a8fb1a54788f7d53128832188de055af4be2b0eca"

      def install
        bin.install "amictl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.1/amictl_0.0.1_darwin_arm64.tar.gz"
      sha256 "eee4de58321359993203a901f8ece616a5210d2cca8f79bbc0bbc25d02a13cf7"

      def install
        bin.install "amictl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.1/amictl_0.0.1_linux_amd64.tar.gz"
      sha256 "685c14c8fdbd05e1be98b5701c4631848594401fa5fdf336eda547bd6c994039"

      def install
        bin.install "amictl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.1/amictl_0.0.1_linux_arm64.tar.gz"
      sha256 "a7a9981e4ddc7da10627badbd80d6645019b3e53679342617af689597f40f4f0"

      def install
        bin.install "amictl"
      end
    end
  end

  test do
    system "#{bin}/amictl --help"
  end
end
