# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amictl < Formula
  desc "amictl"
  homepage "https://github.com/bwagner5/amictl"
  version "0.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.2/amictl_0.0.2_darwin_arm64.tar.gz"
      sha256 "f7e743a97d753f1ccecec8df2ded92e7c3c5eb50a672488441025b0e94b1cf9c"

      def install
        bin.install "amictl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.2/amictl_0.0.2_darwin_amd64.tar.gz"
      sha256 "168e36061ac61ea7b943f2a6df95a462fc61d0ab0902254d04baaff265afa3c3"

      def install
        bin.install "amictl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.2/amictl_0.0.2_linux_arm64.tar.gz"
      sha256 "5bcb76a23a2517c7d921f50174080b66aad1cefceb6ce6753546cf80a37daa25"

      def install
        bin.install "amictl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/amictl/releases/download/v0.0.2/amictl_0.0.2_linux_amd64.tar.gz"
      sha256 "9fa3fd3b886160e7b93a7180ee9c6eec63e0231e73506ad3b3a89a6babbf6830"

      def install
        bin.install "amictl"
      end
    end
  end

  test do
    system "#{bin}/amictl --help"
  end
end
