# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dsfmt < Formula
  desc "diskstats formatter for humans"
  homepage "https://github.com/bwagner5/dsfmt"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.5/dsfmt_0.0.5_Darwin_arm64.tar.gz"
      sha256 "780d7aad1953d13c7561b6a7539957df1436e3556efae84a47782888ab438378"

      def install
        bin.install "dsfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.5/dsfmt_0.0.5_Darwin_amd64.tar.gz"
      sha256 "a2d0d80ad6fedd0c3cd6cfd4b9bcbb0b3587f150db7c42d37d765c84e2fcd393"

      def install
        bin.install "dsfmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.5/dsfmt_0.0.5_Linux_arm64.tar.gz"
      sha256 "0260b1562685d1523891bb64ad4428efc072c204f21a2ee7306e82546aeecd43"

      def install
        bin.install "dsfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.5/dsfmt_0.0.5_Linux_amd64.tar.gz"
      sha256 "4547d0a7ea9d89d48dd8c57d992d2cdf8d70050b1652d2a4220b0b67da3a41b2"

      def install
        bin.install "dsfmt"
      end
    end
  end

  def caveats
    <<~EOS
      cat /proc/diskstats | dsfmt
    EOS
  end

  test do
    system "#{bin}/dsfmt --help"
  end
end
