# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dsfmt < Formula
  desc "diskstats formatter for humans"
  homepage "https://github.com/bwagner5/dsfmt"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.6/dsfmt_0.0.6_Darwin_arm64.tar.gz"
      sha256 "fa98828ef4209f8c30a1a817320dab8a02efb733eb1ddab58da94dffb0d202b0"

      def install
        bin.install "dsfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.6/dsfmt_0.0.6_Darwin_amd64.tar.gz"
      sha256 "95b4ec0693fa3d751f3787199b9e51c30d38740c0c1a278cbb1ea86725a3888e"

      def install
        bin.install "dsfmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.6/dsfmt_0.0.6_Linux_arm64.tar.gz"
      sha256 "28222ff5cc5e0d38857e063b2301f253995439de5d3a42e8e4cd5056ff89575f"

      def install
        bin.install "dsfmt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/dsfmt/releases/download/v0.0.6/dsfmt_0.0.6_Linux_amd64.tar.gz"
      sha256 "7ec23e973b851b6deeb8f624df2abc77e70874295640e5e4ea0f97b3918dae70"

      def install
        bin.install "dsfmt"
      end
    end
  end

  def caveats
    <<~EOS
      cat /proc/diskstats | dsfmt
    EOS
  end

  test do
    system "#{bin}/dsfmt --help"
  end
end
