# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec2ReplacementSim < Formula
  desc "ec2-replacement-sim"
  homepage "https://github.com/bwagner5/ec2-replacement-sim"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/ec2-replacement-sim/releases/download/v0.0.1/ec2-replacement-sim_0.0.1_darwin_arm64.tar.gz"
      sha256 "2eabb4c21c73eb1f51a34f52906744eb71c48920d1b31e08cbc914018a08d322"

      def install
        bin.install "ec2-replacement-sim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/ec2-replacement-sim/releases/download/v0.0.1/ec2-replacement-sim_0.0.1_darwin_amd64.tar.gz"
      sha256 "10d23493eeec743d7270bd239ae21bda580fb818f05ed6bb59c292bc7a017af2"

      def install
        bin.install "ec2-replacement-sim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/ec2-replacement-sim/releases/download/v0.0.1/ec2-replacement-sim_0.0.1_linux_arm64.tar.gz"
      sha256 "bf0339aff7f77b489ea07fae9d79c9730a7f633712ccb4a0cadf6f5e03498408"

      def install
        bin.install "ec2-replacement-sim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/ec2-replacement-sim/releases/download/v0.0.1/ec2-replacement-sim_0.0.1_linux_amd64.tar.gz"
      sha256 "577aa042ae97f5b269bec197a3219df9d6f9b7fe44f71fbd262e363587f19c88"

      def install
        bin.install "ec2-replacement-sim"
      end
    end
  end

  test do
    system "#{bin}/ec2-replacement-sim --help"
  end
end
