# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kompat < Formula
  desc "kompat"
  homepage "https://github.com/bwagner5/kompat"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/kompat/releases/download/v0.0.1/kompat_0.0.1_darwin_arm64.tar.gz"
      sha256 "c2d1d350141aa476a05bfde11f1851428143937eb33cf6186eefd66614dcb8a6"

      def install
        bin.install "kompat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/kompat/releases/download/v0.0.1/kompat_0.0.1_darwin_amd64.tar.gz"
      sha256 "6160ac0b6e9cd47b388ad5bdd2e844abfa9b7568ea2f3b082ee2c09d0bc4415d"

      def install
        bin.install "kompat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/kompat/releases/download/v0.0.1/kompat_0.0.1_linux_arm64.tar.gz"
      sha256 "7113fb81537eeab028171e1d5bfe3346474464529bc3080a40aaec0b3bf68716"

      def install
        bin.install "kompat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/kompat/releases/download/v0.0.1/kompat_0.0.1_linux_amd64.tar.gz"
      sha256 "9ff335b07b1c844be353bc1712de670c856448535849dd535c0032bfee4f779d"

      def install
        bin.install "kompat"
      end
    end
  end

  test do
    system "#{bin}/kompat --help"
  end
end
