# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quant < Formula
  desc "an SI numeric conversion and display tool"
  homepage "https://github.com/bwagner5/quant"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.8/quant_0.0.8_darwin_arm64.tar.gz"
      sha256 "0c78793af0721b8770b2151378c32ea2e3205bcab2ef2d13fa3afb626937fb9a"

      def install
        bin.install "quant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.8/quant_0.0.8_darwin_amd64.tar.gz"
      sha256 "430ab441eeb35a928b1d32fd6f4aa0f5803c19ab1bca196a8f1b8e5228801e12"

      def install
        bin.install "quant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.8/quant_0.0.8_linux_arm64.tar.gz"
      sha256 "14ac714e45d6feb02f6212eec91d6d5f144446ab27073761c1e1eb3ac3596920"

      def install
        bin.install "quant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.8/quant_0.0.8_linux_amd64.tar.gz"
      sha256 "8b4147c5766ed145eab26f5947f5edd367db6410a6068bbc7d5aaa6734e8ee97"

      def install
        bin.install "quant"
      end
    end
  end

  def caveats
    <<~EOS
      quant 1024Ki
    EOS
  end

  test do
    system "#{bin}/quant --help"
  end
end
