# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Quant < Formula
  desc "an SI numeric conversion and display tool"
  homepage "https://github.com/bwagner5/quant"
  version "0.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.7/quant_0.0.7_darwin_amd64.tar.gz"
      sha256 "46e113e125bc4ccff2e9f1638d0c7999da6f8aa693a3cb3485f39fe52c004ec3"

      def install
        bin.install "quant"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.7/quant_0.0.7_darwin_arm64.tar.gz"
      sha256 "1424fc8d8f6492ad7cbc10572d035490a5a9c64c25ae1eee774553fc09c2b648"

      def install
        bin.install "quant"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.7/quant_0.0.7_linux_arm64.tar.gz"
      sha256 "8ce1cd7d920e1a22d1d4ca20532d56350fd633f51d1a1ea0307a7b6b8e2eff7e"

      def install
        bin.install "quant"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/quant/releases/download/v0.0.7/quant_0.0.7_linux_amd64.tar.gz"
      sha256 "a6a5824492219bc798b4e53feaf34a0bed9e7c3213e1aac37d774af0f66fedd3"

      def install
        bin.install "quant"
      end
    end
  end

  def caveats
    <<~EOS
      quant 1024Ki
    EOS
  end

  test do
    system "#{bin}/quant --help"
  end
end
