# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vpcctl < Formula
  desc "a VPC management tool"
  homepage "https://github.com/bwagner5/vpcctl"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/bwagner5/vpcctl/releases/download/v0.0.5/vpcctl_0.0.5_darwin_arm64.tar.gz"
      sha256 "ab86f36c2ffc10c46f4896b72ffbb61afb1098e5cfd19f46031fccf0fc108a8c"

      def install
        bin.install "vpcctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/vpcctl/releases/download/v0.0.5/vpcctl_0.0.5_darwin_amd64.tar.gz"
      sha256 "04b738882e5bfecb700ce36ffc83d1ac90769e017f0de550c2c7fb3ca125807c"

      def install
        bin.install "vpcctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bwagner5/vpcctl/releases/download/v0.0.5/vpcctl_0.0.5_linux_arm64.tar.gz"
      sha256 "2bc4ef630203c151772692839dce99b4d779694f073fabdb64fb4e445c3b665d"

      def install
        bin.install "vpcctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bwagner5/vpcctl/releases/download/v0.0.5/vpcctl_0.0.5_linux_amd64.tar.gz"
      sha256 "656a6c50eeb36a3c195a952f4fd028bce1528828f39eb76f71363053fcca2116"

      def install
        bin.install "vpcctl"
      end
    end
  end

  def caveats
    <<~EOS
      vpcctl --help
    EOS
  end

  test do
    system "#{bin}/vpcctl --help"
  end
end
