# This file was generated by GoReleaser. DO NOT EDIT.
cask "imds" do
  name "imds"
  desc "CLI and TUI for EC2 Instance Metadata Service (IMDS)"
  homepage "https://github.com/bwagner5/imds"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imds"

  on_macos do
    on_intel do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_darwin_amd64.tar.gz"
      sha256 "c727320e7a8a5713d7ae5fefbf51abfe803da9c26b5f9634c2df53172fa544bc"
    end
    on_arm do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_darwin_arm64.tar.gz"
      sha256 "2961ef9628ad04f304008321e65d45d42c1fc0bb89c73a3b37d9771060d7fd11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_linux_amd64.tar.gz"
      sha256 "741507c2505e026192fdf7cfcbaf312d716c13a3a666d427f94a465c215332a9"
    end
    on_arm do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_linux_arm64.tar.gz"
      sha256 "bd6b1dfc585da9aee6a26d558e9f101342815d44db7a48a421ef49e63332eb4f"
    end
  end

  # No zap stanza required
end
