# This file was generated by GoReleaser. DO NOT EDIT.
cask "imds" do
  name "imds"
  desc "CLI and TUI for EC2 Instance Metadata Service (IMDS)"
  homepage "https://github.com/bwagner5/imds"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "imds"

  on_macos do
    on_intel do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_darwin_amd64.tar.gz"
      sha256 "2e2d14651866ba48b548f1bee1ece4f49f68260c129f48b62b08492d85656396"
    end
    on_arm do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_darwin_arm64.tar.gz"
      sha256 "4739ac0fccb1c2fc2140f8afe03afedde6136788a9ca934c95f5212092b701fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_linux_amd64.tar.gz"
      sha256 "0a6182f80903fd8aa814eea2f70a045ef7d64e420bf08b8824bdfea786dc1cf2"
    end
    on_arm do
      url "https://github.com/bwagner5/imds/releases/download/v#{version}/imds_#{version}_linux_arm64.tar.gz"
      sha256 "8d233dda30c812aee14ed3887830959e1181f4014ae33976235c254830bfdef2"
    end
  end

  # No zap stanza required
end
